version: '3'

services: 
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: ./docker/containers/frontend/Dockerfile
      args:
        - NODE_ENV=local
    ports:
      - "4200:4200"
    networks:
      docker-net:
        ipv4_address: "10.5.0.7"
    env_file: ./frontend/.env
    links:
      - backend

  backend:
    container_name: backend
    restart: always
    # Environment variable file
    env_file: ./backend/.env
    build:
      # Current folder is root folder
      context: ./backend
      # Path of dockerfile
      dockerfile: ./docker/Dockerfile
      args:
        - NODE_ENV=local
    volumes:
      - .backend/:/opt/app:rw  
    # api binging ports
    ports:
      - "9000:9000"  
    # Network settings  
    networks:
      docker-net:
        ipv4_address: "10.5.0.6"
    env_file: ./backend/.env
   

  nginx:
    container_name: nginx
    build: ./frontend/docker/containers/nginx
    restart: always
    ports:
      - "80:80"
    networks:
      docker-net:
        ipv4_address: "10.5.0.5"
    links:
      - frontend
    
   
networks:
  docker-net:
    ipam:
      driver: default
      # Subnnet CIDR address
      config:
        - subnet: 10.5.0.0/16
  